#
# OrangeFox device configuration for NX769J (RedMagic 9 Pro)
#

DEVICE_PATH := device/nubia/NX769J
$(call inherit-product, $(DEVICE_PATH)/device.mk)

PRODUCT_RELEASE_NAME := NX769J
PRODUCT_DEVICE := NX769J
PRODUCT_NAME := orangefox_NX769J
PRODUCT_BRAND := nubia
PRODUCT_MODEL := RedMagic 9 Pro
PRODUCT_MANUFACTURER := nubia
TARGET_OTA_ASSERT_DEVICE := NX769J

# Theme/UI
TW_THEME := portrait_hdpi
TW_STATUS_ICONS_ALIGN := center
TW_DEFAULT_LANGUAGE := en
TW_USE_TOOLBOX := 1

# OrangeFox core configs
FOX_BUILD_DEVICE := NX769J
FOX_VERSION := R12.1
FOX_BUILD_TYPE := Official
FOX_MAINTAINER := YourNameHere

# A/B & Dynamic partitions
FOX_AB_DEVICE := 1
FOX_VIRTUAL_AB_DEVICE := 1
OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_PATCH_AVB20 := 1
OF_USE_NEW_MAGISKBOOT := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1

# Magisk & OTA
OF_INCLUDE_MAGISK := 1
OF_FORCE_MAGISKBOOT_BOOT_PATCH_MIUI := 1
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
OF_NO_MIUI_OTA_VENDOR_BACKUP := 1
OF_OTA_BACKUP_STOCK_BOOT_IMAGE := 1

# Encryption/FBE
TW_INCLUDE_CRYPTO := 1
TW_INCLUDE_CRYPTO_FBE := 1
TW_INCLUDE_FBE_METADATA_DECRYPT := 1
TW_USE_FSCRYPT_POLICY := 3

# Filesystem tools
TW_INCLUDE_RESETPROP := 1
TW_INCLUDE_LIBRESETPROP := 1
TW_INCLUDE_FUSE_EXFAT := 1
TW_INCLUDE_FUSE_NTFS := 1
TW_INCLUDE_LPDUMP := 1

# Logging
TWRP_INCLUDE_LOGCAT := 1
TARGET_USES_LOGD := true

# Display
TARGET_SCREEN_DENSITY := 480
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1000

# Security patch (for AVB)
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
BOOT_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 16.1.0

# Maintainer info
OF_MAINTAINER := AJU
